export enum DataType {
	UNIQUE_IDENTIFIER = 'UNIQUEIDENTIFIER',
	BIGINT = 'BIGINT',
	VARCHAR = 'VARCHAR',
	INT = 'INT',
	TINY_INT = 'TINYINT',
	BIT = 'BIT',
	DATE = 'DATE',
	DECIMAL = 'DECIMAL',
	DATE_TIME = 'DATETIME',
	CHAR = 'CHAR',
	SMALLINT = 'SMALLINT'
}
